package com.xx.shop.dao;

import com.xx.shop.entity.Payment;
import com.xx.shop.entity.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    long countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int deleteByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int insert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    Payment selectByPrimaryKey(Long payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int updateByExample(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int updateByPrimaryKeySelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    int updateByPrimaryKey(Payment record);
}