package com.xx.shop.dao;

import com.xx.shop.entity.ShopCart;
import com.xx.shop.entity.ShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    long countByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int deleteByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int deleteByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    List<ShopCart> selectByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    ShopCart selectByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int updateByExample(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopcart
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    int updateByPrimaryKey(ShopCart record);
}