package com.xx.shop.dao;

import com.xx.shop.entity.SkillDetail;
import com.xx.shop.entity.SkillDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    long countByExample(SkillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int deleteByExample(SkillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int insert(SkillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int insertSelective(SkillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    List<SkillDetail> selectByExample(SkillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    SkillDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") SkillDetail record, @Param("example") SkillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int updateByExample(@Param("record") SkillDetail record, @Param("example") SkillDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int updateByPrimaryKeySelective(SkillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    int updateByPrimaryKey(SkillDetail record);
}