package com.xx.shop.dao;

import com.xx.shop.entity.Skill;
import com.xx.shop.entity.SkillExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    long countByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int deleteByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int deleteByPrimaryKey(Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    List<Skill> selectByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    Skill selectByPrimaryKey(Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int updateByExample(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    int updateByPrimaryKey(Skill record);
}