mybatis:
  typeAliasesPackage: com.xx.shop.dao
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://www.wxxandxyx.cn:8888/mall?autoReconnect=true
                      &useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&
                      failOverReadOnly=false
  redis:
    port: 8889
    host: www.wxxandxyx.cn
    connectionTimeout: 5000
    soTimeout: 5000
    database: 0

web:
  config:
    uploadpath: classpath:/resources/

server:
  port: 8081
  servlet:
    context-path: /shop

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


