package com.xx.shop.entity;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.user_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.consignee
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.mobile
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.provice
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String provice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.city
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.town
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String town;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.isdefault
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private byte[] isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_address
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address_id
     *
     * @return the value of t_address.address_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address_id
     *
     * @param addressId the value for t_address.address_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.user_id
     *
     * @return the value of t_address.user_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.user_id
     *
     * @param userId the value for t_address.user_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.consignee
     *
     * @return the value of t_address.consignee
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.consignee
     *
     * @param consignee the value for t_address.consignee
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.mobile
     *
     * @return the value of t_address.mobile
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.mobile
     *
     * @param mobile the value for t_address.mobile
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.provice
     *
     * @return the value of t_address.provice
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.provice
     *
     * @param provice the value for t_address.provice
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setProvice(String provice) {
        this.provice = provice == null ? null : provice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.city
     *
     * @return the value of t_address.city
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.city
     *
     * @param city the value for t_address.city
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.town
     *
     * @return the value of t_address.town
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.town
     *
     * @param town the value for t_address.town
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address
     *
     * @return the value of t_address.address
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address
     *
     * @param address the value for t_address.address
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.isdefault
     *
     * @return the value of t_address.isdefault
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public byte[] getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.isdefault
     *
     * @param isdefault the value for t_address.isdefault
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setIsdefault(byte[] isdefault) {
        this.isdefault = isdefault;
    }
}