package com.xx.shop.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.order_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.product_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.num
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.category_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.store_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.pro_name
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.pro_showing
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private String proShowing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.original_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.favorable_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private BigDecimal favorablePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.isreview
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Integer isreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.ceate_time
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private Date ceateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_detail
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.id
     *
     * @return the value of t_order_detail.id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.id
     *
     * @param id the value for t_order_detail.id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.order_id
     *
     * @return the value of t_order_detail.order_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.order_id
     *
     * @param orderId the value for t_order_detail.order_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.product_id
     *
     * @return the value of t_order_detail.product_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.product_id
     *
     * @param productId the value for t_order_detail.product_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.num
     *
     * @return the value of t_order_detail.num
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.num
     *
     * @param num the value for t_order_detail.num
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.category_id
     *
     * @return the value of t_order_detail.category_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.category_id
     *
     * @param categoryId the value for t_order_detail.category_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.store_id
     *
     * @return the value of t_order_detail.store_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.store_id
     *
     * @param storeId the value for t_order_detail.store_id
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.pro_name
     *
     * @return the value of t_order_detail.pro_name
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.pro_name
     *
     * @param proName the value for t_order_detail.pro_name
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.pro_showing
     *
     * @return the value of t_order_detail.pro_showing
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public String getProShowing() {
        return proShowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.pro_showing
     *
     * @param proShowing the value for t_order_detail.pro_showing
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setProShowing(String proShowing) {
        this.proShowing = proShowing == null ? null : proShowing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.original_price
     *
     * @return the value of t_order_detail.original_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.original_price
     *
     * @param originalPrice the value for t_order_detail.original_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.favorable_price
     *
     * @return the value of t_order_detail.favorable_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public BigDecimal getFavorablePrice() {
        return favorablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.favorable_price
     *
     * @param favorablePrice the value for t_order_detail.favorable_price
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setFavorablePrice(BigDecimal favorablePrice) {
        this.favorablePrice = favorablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.isreview
     *
     * @return the value of t_order_detail.isreview
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Integer getIsreview() {
        return isreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.isreview
     *
     * @param isreview the value for t_order_detail.isreview
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setIsreview(Integer isreview) {
        this.isreview = isreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.ceate_time
     *
     * @return the value of t_order_detail.ceate_time
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public Date getCeateTime() {
        return ceateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.ceate_time
     *
     * @param ceateTime the value for t_order_detail.ceate_time
     *
     * @mbg.generated Mon Mar 19 21:54:49 CST 2018
     */
    public void setCeateTime(Date ceateTime) {
        this.ceateTime = ceateTime;
    }
}