package com.xx.shop.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Short orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Short shippingState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Short payState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.product_num
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String payNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_system_name
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String paySystemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.consignee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.address
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.zipcode
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private BigDecimal shipfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private BigDecimal payfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.cutfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private BigDecimal cutfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delivery_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.transaction_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date transactionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.close_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_state
     *
     * @return the value of t_order.order_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Short getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_state
     *
     * @param orderState the value for t_order.order_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setOrderState(Short orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_state
     *
     * @return the value of t_order.shipping_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Short getShippingState() {
        return shippingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_state
     *
     * @param shippingState the value for t_order.shipping_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setShippingState(Short shippingState) {
        this.shippingState = shippingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_state
     *
     * @return the value of t_order.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Short getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_state
     *
     * @param payState the value for t_order.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayState(Short payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.product_num
     *
     * @return the value of t_order.product_num
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.product_num
     *
     * @param productNum the value for t_order.product_num
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_no
     *
     * @return the value of t_order.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_no
     *
     * @param payNo the value for t_order.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_system_name
     *
     * @return the value of t_order.pay_system_name
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getPaySystemName() {
        return paySystemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_system_name
     *
     * @param paySystemName the value for t_order.pay_system_name
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPaySystemName(String paySystemName) {
        this.paySystemName = paySystemName == null ? null : paySystemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.consignee
     *
     * @return the value of t_order.consignee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.consignee
     *
     * @param consignee the value for t_order.consignee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.mobile
     *
     * @return the value of t_order.mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.mobile
     *
     * @param mobile the value for t_order.mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.address
     *
     * @return the value of t_order.address
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.address
     *
     * @param address the value for t_order.address
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.zipcode
     *
     * @return the value of t_order.zipcode
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.zipcode
     *
     * @param zipcode the value for t_order.zipcode
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipfee
     *
     * @return the value of t_order.shipfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public BigDecimal getShipfee() {
        return shipfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipfee
     *
     * @param shipfee the value for t_order.shipfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setShipfee(BigDecimal shipfee) {
        this.shipfee = shipfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payfee
     *
     * @return the value of t_order.payfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public BigDecimal getPayfee() {
        return payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payfee
     *
     * @param payfee the value for t_order.payfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayfee(BigDecimal payfee) {
        this.payfee = payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.cutfee
     *
     * @return the value of t_order.cutfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public BigDecimal getCutfee() {
        return cutfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.cutfee
     *
     * @param cutfee the value for t_order.cutfee
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setCutfee(BigDecimal cutfee) {
        this.cutfee = cutfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delivery_time
     *
     * @return the value of t_order.delivery_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delivery_time
     *
     * @param deliveryTime the value for t_order.delivery_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.transaction_time
     *
     * @return the value of t_order.transaction_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.transaction_time
     *
     * @param transactionTime the value for t_order.transaction_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.close_time
     *
     * @return the value of t_order.close_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.close_time
     *
     * @param closeTime the value for t_order.close_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }
}