package com.xx.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class Payment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.pay_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.order_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.pay_platform
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Byte payPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String payNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Byte payState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_payment
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.pay_id
     *
     * @return the value of t_payment.pay_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.pay_id
     *
     * @param payId the value for t_payment.pay_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.user_id
     *
     * @return the value of t_payment.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.user_id
     *
     * @param userId the value for t_payment.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.order_no
     *
     * @return the value of t_payment.order_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.order_no
     *
     * @param orderNo the value for t_payment.order_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.pay_platform
     *
     * @return the value of t_payment.pay_platform
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Byte getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.pay_platform
     *
     * @param payPlatform the value for t_payment.pay_platform
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayPlatform(Byte payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.pay_no
     *
     * @return the value of t_payment.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.pay_no
     *
     * @param payNo the value for t_payment.pay_no
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.pay_state
     *
     * @return the value of t_payment.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Byte getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.pay_state
     *
     * @param payState the value for t_payment.pay_state
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPayState(Byte payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.create_time
     *
     * @return the value of t_payment.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.create_time
     *
     * @param createTime the value for t_payment.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.update_time
     *
     * @return the value of t_payment.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.update_time
     *
     * @param updateTime the value for t_payment.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}