package com.xx.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class PointLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_log.logid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_log.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_log.point
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_log.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_point_log
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_log.logid
     *
     * @return the value of t_point_log.logid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_log.logid
     *
     * @param logid the value for t_point_log.logid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_log.user_id
     *
     * @return the value of t_point_log.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_log.user_id
     *
     * @param userId the value for t_point_log.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_log.point
     *
     * @return the value of t_point_log.point
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_log.point
     *
     * @param point the value for t_point_log.point
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_log.create_time
     *
     * @return the value of t_point_log.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_log.create_time
     *
     * @param createTime the value for t_point_log.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}