package com.xx.shop.entity;

import java.io.Serializable;

public class ProductWithBLOBs extends Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.isbest
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private byte[] isbest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.ishot
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private byte[] ishot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.isbest
     *
     * @return the value of t_product.isbest
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public byte[] getIsbest() {
        return isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.isbest
     *
     * @param isbest the value for t_product.isbest
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setIsbest(byte[] isbest) {
        this.isbest = isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.ishot
     *
     * @return the value of t_product.ishot
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public byte[] getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.ishot
     *
     * @param ishot the value for t_product.ishot
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setIshot(byte[] ishot) {
        this.ishot = ishot;
    }
}