package com.xx.shop.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     * @param s
     */
    public List<Criteria> getOredCriteria(String s) {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Long value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Long value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Long value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Long value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Long value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Long value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Long> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Long> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Long value1, Long value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Long value1, Long value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPsnIsNull() {
            addCriterion("psn is null");
            return (Criteria) this;
        }

        public Criteria andPsnIsNotNull() {
            addCriterion("psn is not null");
            return (Criteria) this;
        }

        public Criteria andPsnEqualTo(Integer value) {
            addCriterion("psn =", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnNotEqualTo(Integer value) {
            addCriterion("psn <>", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnGreaterThan(Integer value) {
            addCriterion("psn >", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnGreaterThanOrEqualTo(Integer value) {
            addCriterion("psn >=", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnLessThan(Integer value) {
            addCriterion("psn <", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnLessThanOrEqualTo(Integer value) {
            addCriterion("psn <=", value, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnIn(List<Integer> values) {
            addCriterion("psn in", values, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnNotIn(List<Integer> values) {
            addCriterion("psn not in", values, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnBetween(Integer value1, Integer value2) {
            addCriterion("psn between", value1, value2, "psn");
            return (Criteria) this;
        }

        public Criteria andPsnNotBetween(Integer value1, Integer value2) {
            addCriterion("psn not between", value1, value2, "psn");
            return (Criteria) this;
        }

        public Criteria andCateIsNull() {
            addCriterion("cate is null");
            return (Criteria) this;
        }

        public Criteria andCateIsNotNull() {
            addCriterion("cate is not null");
            return (Criteria) this;
        }

        public Criteria andCateEqualTo(Integer value) {
            addCriterion("cate =", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateNotEqualTo(Integer value) {
            addCriterion("cate <>", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateGreaterThan(Integer value) {
            addCriterion("cate >", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateGreaterThanOrEqualTo(Integer value) {
            addCriterion("cate >=", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateLessThan(Integer value) {
            addCriterion("cate <", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateLessThanOrEqualTo(Integer value) {
            addCriterion("cate <=", value, "cate");
            return (Criteria) this;
        }

        public Criteria andCateIn(List<Integer> values) {
            addCriterion("cate in", values, "cate");
            return (Criteria) this;
        }

        public Criteria andCateNotIn(List<Integer> values) {
            addCriterion("cate not in", values, "cate");
            return (Criteria) this;
        }

        public Criteria andCateBetween(Integer value1, Integer value2) {
            addCriterion("cate between", value1, value2, "cate");
            return (Criteria) this;
        }

        public Criteria andCateNotBetween(Integer value1, Integer value2) {
            addCriterion("cate not between", value1, value2, "cate");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeid is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeid is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Long value) {
            addCriterion("storeid =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Long value) {
            addCriterion("storeid <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Long value) {
            addCriterion("storeid >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Long value) {
            addCriterion("storeid >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Long value) {
            addCriterion("storeid <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Long value) {
            addCriterion("storeid <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Long> values) {
            addCriterion("storeid in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Long> values) {
            addCriterion("storeid not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Long value1, Long value2) {
            addCriterion("storeid between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Long value1, Long value2) {
            addCriterion("storeid not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceIsNull() {
            addCriterion("favourable_price is null");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceIsNotNull() {
            addCriterion("favourable_price is not null");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceEqualTo(BigDecimal value) {
            addCriterion("favourable_price =", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceNotEqualTo(BigDecimal value) {
            addCriterion("favourable_price <>", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceGreaterThan(BigDecimal value) {
            addCriterion("favourable_price >", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("favourable_price >=", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceLessThan(BigDecimal value) {
            addCriterion("favourable_price <", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("favourable_price <=", value, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceIn(List<BigDecimal> values) {
            addCriterion("favourable_price in", values, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceNotIn(List<BigDecimal> values) {
            addCriterion("favourable_price not in", values, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("favourable_price between", value1, value2, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andFavourablePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("favourable_price not between", value1, value2, "favourablePrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("original_price is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("original_price is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(BigDecimal value) {
            addCriterion("original_price =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(BigDecimal value) {
            addCriterion("original_price <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(BigDecimal value) {
            addCriterion("original_price >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(BigDecimal value) {
            addCriterion("original_price <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<BigDecimal> values) {
            addCriterion("original_price in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<BigDecimal> values) {
            addCriterion("original_price not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andIsbestIsNull() {
            addCriterion("isbest is null");
            return (Criteria) this;
        }

        public Criteria andIsbestIsNotNull() {
            addCriterion("isbest is not null");
            return (Criteria) this;
        }

        public Criteria andIsbestEqualTo(Integer value) {
            addCriterion("isbest =", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestNotEqualTo(Integer value) {
            addCriterion("isbest <>", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestGreaterThan(Integer value) {
            addCriterion("isbest >", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestGreaterThanOrEqualTo(Integer value) {
            addCriterion("isbest >=", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestLessThan(Integer value) {
            addCriterion("isbest <", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestLessThanOrEqualTo(Integer value) {
            addCriterion("isbest <=", value, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestIn(List<Integer> values) {
            addCriterion("isbest in", values, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestNotIn(List<Integer> values) {
            addCriterion("isbest not in", values, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestBetween(Integer value1, Integer value2) {
            addCriterion("isbest between", value1, value2, "isbest");
            return (Criteria) this;
        }

        public Criteria andIsbestNotBetween(Integer value1, Integer value2) {
            addCriterion("isbest not between", value1, value2, "isbest");
            return (Criteria) this;
        }

        public Criteria andIshotIsNull() {
            addCriterion("ishot is null");
            return (Criteria) this;
        }

        public Criteria andIshotIsNotNull() {
            addCriterion("ishot is not null");
            return (Criteria) this;
        }

        public Criteria andIshotEqualTo(Integer value) {
            addCriterion("ishot =", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotNotEqualTo(Integer value) {
            addCriterion("ishot <>", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotGreaterThan(Integer value) {
            addCriterion("ishot >", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotGreaterThanOrEqualTo(Integer value) {
            addCriterion("ishot >=", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotLessThan(Integer value) {
            addCriterion("ishot <", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotLessThanOrEqualTo(Integer value) {
            addCriterion("ishot <=", value, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotIn(List<Integer> values) {
            addCriterion("ishot in", values, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotNotIn(List<Integer> values) {
            addCriterion("ishot not in", values, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotBetween(Integer value1, Integer value2) {
            addCriterion("ishot between", value1, value2, "ishot");
            return (Criteria) this;
        }

        public Criteria andIshotNotBetween(Integer value1, Integer value2) {
            addCriterion("ishot not between", value1, value2, "ishot");
            return (Criteria) this;
        }

        public Criteria andShowimageIsNull() {
            addCriterion("showimage is null");
            return (Criteria) this;
        }

        public Criteria andShowimageIsNotNull() {
            addCriterion("showimage is not null");
            return (Criteria) this;
        }

        public Criteria andShowimageEqualTo(String value) {
            addCriterion("showimage =", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageNotEqualTo(String value) {
            addCriterion("showimage <>", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageGreaterThan(String value) {
            addCriterion("showimage >", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageGreaterThanOrEqualTo(String value) {
            addCriterion("showimage >=", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageLessThan(String value) {
            addCriterion("showimage <", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageLessThanOrEqualTo(String value) {
            addCriterion("showimage <=", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageLike(String value) {
            addCriterion("showimage like", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageNotLike(String value) {
            addCriterion("showimage not like", value, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageIn(List<String> values) {
            addCriterion("showimage in", values, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageNotIn(List<String> values) {
            addCriterion("showimage not in", values, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageBetween(String value1, String value2) {
            addCriterion("showimage between", value1, value2, "showimage");
            return (Criteria) this;
        }

        public Criteria andShowimageNotBetween(String value1, String value2) {
            addCriterion("showimage not between", value1, value2, "showimage");
            return (Criteria) this;
        }

        public Criteria andSalecountIsNull() {
            addCriterion("salecount is null");
            return (Criteria) this;
        }

        public Criteria andSalecountIsNotNull() {
            addCriterion("salecount is not null");
            return (Criteria) this;
        }

        public Criteria andSalecountEqualTo(Integer value) {
            addCriterion("salecount =", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotEqualTo(Integer value) {
            addCriterion("salecount <>", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountGreaterThan(Integer value) {
            addCriterion("salecount >", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("salecount >=", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountLessThan(Integer value) {
            addCriterion("salecount <", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountLessThanOrEqualTo(Integer value) {
            addCriterion("salecount <=", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountIn(List<Integer> values) {
            addCriterion("salecount in", values, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotIn(List<Integer> values) {
            addCriterion("salecount not in", values, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountBetween(Integer value1, Integer value2) {
            addCriterion("salecount between", value1, value2, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotBetween(Integer value1, Integer value2) {
            addCriterion("salecount not between", value1, value2, "salecount");
            return (Criteria) this;
        }

        public Criteria andVisitcountIsNull() {
            addCriterion("visitcount is null");
            return (Criteria) this;
        }

        public Criteria andVisitcountIsNotNull() {
            addCriterion("visitcount is not null");
            return (Criteria) this;
        }

        public Criteria andVisitcountEqualTo(Integer value) {
            addCriterion("visitcount =", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountNotEqualTo(Integer value) {
            addCriterion("visitcount <>", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountGreaterThan(Integer value) {
            addCriterion("visitcount >", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("visitcount >=", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountLessThan(Integer value) {
            addCriterion("visitcount <", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountLessThanOrEqualTo(Integer value) {
            addCriterion("visitcount <=", value, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountIn(List<Integer> values) {
            addCriterion("visitcount in", values, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountNotIn(List<Integer> values) {
            addCriterion("visitcount not in", values, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountBetween(Integer value1, Integer value2) {
            addCriterion("visitcount between", value1, value2, "visitcount");
            return (Criteria) this;
        }

        public Criteria andVisitcountNotBetween(Integer value1, Integer value2) {
            addCriterion("visitcount not between", value1, value2, "visitcount");
            return (Criteria) this;
        }

        public Criteria andStart1IsNull() {
            addCriterion("start1 is null");
            return (Criteria) this;
        }

        public Criteria andStart1IsNotNull() {
            addCriterion("start1 is not null");
            return (Criteria) this;
        }

        public Criteria andStart1EqualTo(Integer value) {
            addCriterion("start1 =", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1NotEqualTo(Integer value) {
            addCriterion("start1 <>", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1GreaterThan(Integer value) {
            addCriterion("start1 >", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1GreaterThanOrEqualTo(Integer value) {
            addCriterion("start1 >=", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1LessThan(Integer value) {
            addCriterion("start1 <", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1LessThanOrEqualTo(Integer value) {
            addCriterion("start1 <=", value, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1In(List<Integer> values) {
            addCriterion("start1 in", values, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1NotIn(List<Integer> values) {
            addCriterion("start1 not in", values, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1Between(Integer value1, Integer value2) {
            addCriterion("start1 between", value1, value2, "start1");
            return (Criteria) this;
        }

        public Criteria andStart1NotBetween(Integer value1, Integer value2) {
            addCriterion("start1 not between", value1, value2, "start1");
            return (Criteria) this;
        }

        public Criteria andStar2IsNull() {
            addCriterion("star2 is null");
            return (Criteria) this;
        }

        public Criteria andStar2IsNotNull() {
            addCriterion("star2 is not null");
            return (Criteria) this;
        }

        public Criteria andStar2EqualTo(Integer value) {
            addCriterion("star2 =", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2NotEqualTo(Integer value) {
            addCriterion("star2 <>", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2GreaterThan(Integer value) {
            addCriterion("star2 >", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2GreaterThanOrEqualTo(Integer value) {
            addCriterion("star2 >=", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2LessThan(Integer value) {
            addCriterion("star2 <", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2LessThanOrEqualTo(Integer value) {
            addCriterion("star2 <=", value, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2In(List<Integer> values) {
            addCriterion("star2 in", values, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2NotIn(List<Integer> values) {
            addCriterion("star2 not in", values, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2Between(Integer value1, Integer value2) {
            addCriterion("star2 between", value1, value2, "star2");
            return (Criteria) this;
        }

        public Criteria andStar2NotBetween(Integer value1, Integer value2) {
            addCriterion("star2 not between", value1, value2, "star2");
            return (Criteria) this;
        }

        public Criteria andStar3IsNull() {
            addCriterion("star3 is null");
            return (Criteria) this;
        }

        public Criteria andStar3IsNotNull() {
            addCriterion("star3 is not null");
            return (Criteria) this;
        }

        public Criteria andStar3EqualTo(Integer value) {
            addCriterion("star3 =", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3NotEqualTo(Integer value) {
            addCriterion("star3 <>", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3GreaterThan(Integer value) {
            addCriterion("star3 >", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3GreaterThanOrEqualTo(Integer value) {
            addCriterion("star3 >=", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3LessThan(Integer value) {
            addCriterion("star3 <", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3LessThanOrEqualTo(Integer value) {
            addCriterion("star3 <=", value, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3In(List<Integer> values) {
            addCriterion("star3 in", values, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3NotIn(List<Integer> values) {
            addCriterion("star3 not in", values, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3Between(Integer value1, Integer value2) {
            addCriterion("star3 between", value1, value2, "star3");
            return (Criteria) this;
        }

        public Criteria andStar3NotBetween(Integer value1, Integer value2) {
            addCriterion("star3 not between", value1, value2, "star3");
            return (Criteria) this;
        }

        public Criteria andStar4IsNull() {
            addCriterion("star4 is null");
            return (Criteria) this;
        }

        public Criteria andStar4IsNotNull() {
            addCriterion("star4 is not null");
            return (Criteria) this;
        }

        public Criteria andStar4EqualTo(Integer value) {
            addCriterion("star4 =", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4NotEqualTo(Integer value) {
            addCriterion("star4 <>", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4GreaterThan(Integer value) {
            addCriterion("star4 >", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4GreaterThanOrEqualTo(Integer value) {
            addCriterion("star4 >=", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4LessThan(Integer value) {
            addCriterion("star4 <", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4LessThanOrEqualTo(Integer value) {
            addCriterion("star4 <=", value, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4In(List<Integer> values) {
            addCriterion("star4 in", values, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4NotIn(List<Integer> values) {
            addCriterion("star4 not in", values, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4Between(Integer value1, Integer value2) {
            addCriterion("star4 between", value1, value2, "star4");
            return (Criteria) this;
        }

        public Criteria andStar4NotBetween(Integer value1, Integer value2) {
            addCriterion("star4 not between", value1, value2, "star4");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(Date value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(Date value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(Date value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(Date value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Date value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<Date> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<Date> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(Date value1, Date value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(Date value1, Date value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_product
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 22 23:08:19 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}