package com.xx.shop.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.pid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.psn
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer psn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.cate
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer cate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.storeid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.favourable_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private BigDecimal favourablePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.original_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.isbest
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer isbest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.ishot
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer ishot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.showimage
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private String showimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.salecount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer salecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.visitcount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer visitcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.start1
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer start1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.star2
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer star2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.star3
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer star3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.star4
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer star4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.addtime
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.description
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.count
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.pid
     *
     * @return the value of t_product.pid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.pid
     *
     * @param pid the value for t_product.pid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.psn
     *
     * @return the value of t_product.psn
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getPsn() {
        return psn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.psn
     *
     * @param psn the value for t_product.psn
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setPsn(Integer psn) {
        this.psn = psn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.cate
     *
     * @return the value of t_product.cate
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getCate() {
        return cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.cate
     *
     * @param cate the value for t_product.cate
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setCate(Integer cate) {
        this.cate = cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.storeid
     *
     * @return the value of t_product.storeid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.storeid
     *
     * @param storeid the value for t_product.storeid
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setStoreid(Long storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.favourable_price
     *
     * @return the value of t_product.favourable_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public BigDecimal getFavourablePrice() {
        return favourablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.favourable_price
     *
     * @param favourablePrice the value for t_product.favourable_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setFavourablePrice(BigDecimal favourablePrice) {
        this.favourablePrice = favourablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.original_price
     *
     * @return the value of t_product.original_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.original_price
     *
     * @param originalPrice the value for t_product.original_price
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.isbest
     *
     * @return the value of t_product.isbest
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getIsbest() {
        return isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.isbest
     *
     * @param isbest the value for t_product.isbest
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setIsbest(Integer isbest) {
        this.isbest = isbest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.ishot
     *
     * @return the value of t_product.ishot
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getIshot() {
        return ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.ishot
     *
     * @param ishot the value for t_product.ishot
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setIshot(Integer ishot) {
        this.ishot = ishot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.showimage
     *
     * @return the value of t_product.showimage
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public String getShowimage() {
        return showimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.showimage
     *
     * @param showimage the value for t_product.showimage
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setShowimage(String showimage) {
        this.showimage = showimage == null ? null : showimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.salecount
     *
     * @return the value of t_product.salecount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getSalecount() {
        return salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.salecount
     *
     * @param salecount the value for t_product.salecount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setSalecount(Integer salecount) {
        this.salecount = salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.visitcount
     *
     * @return the value of t_product.visitcount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.visitcount
     *
     * @param visitcount the value for t_product.visitcount
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.start1
     *
     * @return the value of t_product.start1
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getStart1() {
        return start1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.start1
     *
     * @param start1 the value for t_product.start1
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setStart1(Integer start1) {
        this.start1 = start1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.star2
     *
     * @return the value of t_product.star2
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getStar2() {
        return star2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.star2
     *
     * @param star2 the value for t_product.star2
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setStar2(Integer star2) {
        this.star2 = star2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.star3
     *
     * @return the value of t_product.star3
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getStar3() {
        return star3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.star3
     *
     * @param star3 the value for t_product.star3
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setStar3(Integer star3) {
        this.star3 = star3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.star4
     *
     * @return the value of t_product.star4
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getStar4() {
        return star4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.star4
     *
     * @param star4 the value for t_product.star4
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setStar4(Integer star4) {
        this.star4 = star4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.addtime
     *
     * @return the value of t_product.addtime
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.addtime
     *
     * @param addtime the value for t_product.addtime
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.description
     *
     * @return the value of t_product.description
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.description
     *
     * @param description the value for t_product.description
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.count
     *
     * @return the value of t_product.count
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.count
     *
     * @param count the value for t_product.count
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}