package com.xx.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class SkillDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill_detail.id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill_detail.skill_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long skillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill_detail.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill_detail.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill_detail.ip
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_skill_detail
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill_detail.id
     *
     * @return the value of t_skill_detail.id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill_detail.id
     *
     * @param id the value for t_skill_detail.id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill_detail.skill_id
     *
     * @return the value of t_skill_detail.skill_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill_detail.skill_id
     *
     * @param skillId the value for t_skill_detail.skill_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill_detail.user_id
     *
     * @return the value of t_skill_detail.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill_detail.user_id
     *
     * @param userId the value for t_skill_detail.user_id
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill_detail.create_time
     *
     * @return the value of t_skill_detail.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill_detail.create_time
     *
     * @param createTime the value for t_skill_detail.create_time
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill_detail.ip
     *
     * @return the value of t_skill_detail.ip
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill_detail.ip
     *
     * @param ip the value for t_skill_detail.ip
     *
     * @mbg.generated Thu Mar 22 23:08:19 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}