package com.xx.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class Skill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.skill_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Long skillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.gid
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.state
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.start_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.end_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_skill.count
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_skill
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.skill_id
     *
     * @return the value of t_skill.skill_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.skill_id
     *
     * @param skillId the value for t_skill.skill_id
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.gid
     *
     * @return the value of t_skill.gid
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.gid
     *
     * @param gid the value for t_skill.gid
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.state
     *
     * @return the value of t_skill.state
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.state
     *
     * @param state the value for t_skill.state
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.start_time
     *
     * @return the value of t_skill.start_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.start_time
     *
     * @param startTime the value for t_skill.start_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.end_time
     *
     * @return the value of t_skill.end_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.end_time
     *
     * @param endTime the value for t_skill.end_time
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_skill.count
     *
     * @return the value of t_skill.count
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_skill.count
     *
     * @param count the value for t_skill.count
     *
     * @mbg.generated Thu Mar 15 15:46:48 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}