package com.xx.shop.entity;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.hand_image
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String handImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.level_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_integral
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Integer userIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.store_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nickname
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.verify_mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Byte verifyMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.hand_image
     *
     * @return the value of t_user.hand_image
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getHandImage() {
        return handImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.hand_image
     *
     * @param handImage the value for t_user.hand_image
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setHandImage(String handImage) {
        this.handImage = handImage == null ? null : handImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.level_id
     *
     * @return the value of t_user.level_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.level_id
     *
     * @param levelId the value for t_user.level_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_integral
     *
     * @return the value of t_user.user_integral
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Integer getUserIntegral() {
        return userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_integral
     *
     * @param userIntegral the value for t_user.user_integral
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUserIntegral(Integer userIntegral) {
        this.userIntegral = userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.store_id
     *
     * @return the value of t_user.store_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.store_id
     *
     * @param storeId the value for t_user.store_id
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickname
     *
     * @return the value of t_user.nickname
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickname
     *
     * @param nickname the value for t_user.nickname
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.verify_mobile
     *
     * @return the value of t_user.verify_mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Byte getVerifyMobile() {
        return verifyMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.verify_mobile
     *
     * @param verifyMobile the value for t_user.verify_mobile
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setVerifyMobile(Byte verifyMobile) {
        this.verifyMobile = verifyMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.update_time
     *
     * @return the value of t_user.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.update_time
     *
     * @param updateTime the value for t_user.update_time
     *
     * @mbg.generated Mon Mar 19 21:20:53 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}