mybatis:
  typeAliasesPackage: com.xx.shop.dao
  mapperLocations: classpath:mapper/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://115.217.254.158:8888/mall?autoReconnect=true
                      &useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&
                      failOverReadOnly=false
server:
  port: 8082
  servlet:
    context-path: /shop
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
